#!/bin/bash

GREEN='\033[1;32m'
ORANGE='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Color

cd "$(cd $(dirname $0)/..; pwd)"

changed_files=y
if ls dist/sigenergy2mqtt-*-py3-none-any.whl >/dev/null 2>&1 && [[ $(find sigenergy2mqtt -newer $(ls -t dist/sigenergy2mqtt-*-py3-none-any.whl | head -n 1) -type f -name '*.py' | wc -l) = 0 ]]; then
    changed_files=n
fi
if echo "$*" | grep -vqe "-f" && [[ $changed_files = n ]]; then
    echo -e "${RED}>>> Build CANCELLED: ${ORANGE}No changed files found${NC}"
    exit
fi

echo -e "${GREEN}>>> Checking sensors...${NC}"
python3 -c '
import asyncio
import logging
from tests.utils import get_sensor_instances, cancel_sensor_futures
logging.getLogger("root").setLevel(logging.WARNING)
async def check():
    await get_sensor_instances(hass=True)
    await get_sensor_instances(hass=False)
if __name__ == "__main__":
    loop = asyncio.new_event_loop()
    loop.run_until_complete(check())
    cancel_sensor_futures()
    loop.close()
' || exit

echo -e "${GREEN}>>> Updating documentation...${NC}"
for var in $(grep -Eo '^SIGENERGY2MQTT_[^:]+' sigenergy2mqtt/config/const.py); do
    grep -Eq "| \`${var}\`" resources/configuration/ENV.md || { echo -e "${RED}>>> Environment variable ${ORANGE}$var${RED} not found in ENV.md!"; exit; }
done
date "+%Y-%m-%d %H:%M:%S,000 INFO     sigenergy2mqtt:build..........0086 All environment variables found in resources/configuration/ENV.md"
python3 -c '
import os
import sys
print("# Command Line Options\n")
print("```")
from sigenergy2mqtt.__main__ import main
sys.exit(main())
print("```")
' --help >resources/configuration/CLI.md 2>/dev/null
date "+%Y-%m-%d %H:%M:%S,000 INFO     sigenergy2mqtt:build..........0086 resources/configuration/CLI.md updated"
cd scripts
python3 update_md.py
cd - >> /dev/null

echo -e "${GREEN}>>> Running test suite...${NC}"
pytest -q --disable-warnings || exit

echo -e "${GREEN}>>> Calculating new version...${NC}"
old_version=$(grep __version__ sigenergy2mqtt/config/version.py | cut -d'"' -f2)
if [[ $changed_files = n ]]; then
    new_version=$old_version
    post=$(echo $old_version | cut -d'-' -f2)
    if [[ $post =~ ^[0-9]+$ ]]; then
        pypi_version="$(echo $new_version | cut -d'-' -f1).post$post"
    else
        pypi_version=$old_version
    fi
else
    new_version=$(date +"%Y.%-m.%-d")
    pypi_version=$new_version
    if [[ $old_version =~ ^"$new_version" ]]; then
        post=$(echo $old_version | cut -d'-' -f2)
        if [[ $post =~ ^[0-9]+$ ]]; then
            pypi_version="${new_version}.post$((post + 1))"
            new_version="${new_version}-$((post + 1))"
        else
            pypi_version="${new_version}.post1"
            new_version="${new_version}-1"
        fi
    fi
    sed -e "s/^__version__ = \".*\"/__version__ = \"$new_version\"/g" -i sigenergy2mqtt/config/version.py
    echo -e "    Updated version from ${GREEN}$old_version${NC} to ${GREEN}$new_version (PyPi=$pypi_version)${NC}"
fi

rm -f dist/*

echo -e "${GREEN}>>> Building distribution...${NC}"
python3 -m build || exit
python3 -m twine check dist/* || exit

if [[ -e ../home-assistant-addons/sigenergy2mqtt/config.yaml ]]; then
    echo -e "${GREEN}>>> Updating add-on...${NC}"
    mkdir -p ../home-assistant-addons/sigenergy2mqtt/rootfs/dist
    rm -f ../home-assistant-addons/sigenergy2mqtt/rootfs/dist/sigenergy2mqtt-*.whl
    cp -v dist/sigenergy2mqtt-${pypi_version}-py3-none-any.whl ../home-assistant-addons/sigenergy2mqtt/rootfs/dist/
    sed -e "s/^version: \".*\"/version: \"$new_version\"/g" -i ../home-assistant-addons/sigenergy2mqtt/config.yaml
    sed -e "s/sigenergy2mqtt-.*-py3/sigenergy2mqtt-${pypi_version}-py3/" -i ../home-assistant-addons/sigenergy2mqtt/Dockerfile
fi

echo -e "${GREEN}>>> Build successful${NC} $(date): Old version=${ORANGE}$old_version${NC} New version=${GREEN}$new_version${NC} (PyPi=${GREEN}$pypi_version${NC})"
