#!/bin/bash

cd "$(cd $(dirname $0)/../..; pwd)"
if [[ -z "$VIRTUAL_ENV" ]]; then
   source .venv/bin/activate
fi

python3 -m build || exit
python3 -m twine check dist/* || exit
docker buildx build --platform linux/amd64 --load -t sigenergy2mqtt:latest . || exit

MODE="run"
KEEP=false

for arg in "$@"; do
    if [[ $arg == compose ]]; then
        MODE="compose"
    elif [[ $arg == keep ]]; then
        KEEP=true
    fi
done

if [[ $MODE == compose ]]; then
    cd tests/utils
    docker compose up
else
    docker run -it \
        -e TZ=Australia/Melbourne \
        -e SIGENERGY2MQTT_LOG_LEVEL=DEBUG \
        -e SIGENERGY2MQTT_MODBUS_AUTO_DISCOVERY=once \
        -v /var/lib/sigenergy2mqtt:/data \
        --network host \
        sigenergy2mqtt:latest
fi

if [[ $KEEP == false ]]; then
    docker rmi sigenergy2mqtt:latest
fi
