#!/bin/bash

GREEN='\033[1;32m'
ORANGE='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Colour

cd "$(cd $(dirname $0)/..; pwd)"
if [[ -z "$VIRTUAL_ENV" ]]; then
   source .venv/bin/activate
fi

git restore sigenergy2mqtt/config/version.py

echo -e "${GREEN}>>> Checking dependencies...${NC}"
scripts/dependencies --no-upgrade

source $(dirname $0)/build $*

echo -en "${GREEN}>>> Confirm version bump? (y/n): ${NC}"
read confirm
if [[ "$confirm" != "y" ]]; then
    echo -e "${RED}>>> Version bump cancelled.${NC}"
    git restore sigenergy2mqtt/config/version.py
    touch -d "$(git log -1 --pretty=format:%cI -- sigenergy2mqtt/config/version.py)" sigenergy2mqtt/config/version.py
    exit 1
fi

for file in \
    CHANGELOG.md \
    resources/configuration/CLI.md \
    resources/sensors/SENSORS.md \
    resources/sensors/TOPICS.md \
    sigenergy2mqtt/config/version.py \
    sigenergy2mqtt/sensors/base/_sigenergy_local_modbus_registers.py
do
    if ! git diff --quiet "$file"; then
        git add "$file"
    fi
done
files=$(git diff --name-only --exit-code)
status=$?
if [ $status -ne 0 ]; then
    echo -e "${ORANGE}>>> Uncommitted changes found in the following files:${NC}"
    echo "$files"
    echo -e "${RED}>>> Version bump cancelled.${NC}"
    exit 1
fi

echo -e "${GREEN}>>> Bumping version...${NC}"
git commit -m "build: bump version to $new_version"
git tag "$new_version"
git push && git push --tags
