#!/bin/bash

GREEN='\033[1;32m'
ORANGE='\033[0;33m'
RED='\033[0;31m'
NC='\033[0m' # No Colour

cd "$(cd $(dirname $0)/..; pwd)"

echo -e "${GREEN}>>> Updating English translations...${NC}"
python3 scripts/update_en_translation.py || exit

echo -e "${GREEN}>>> Checking translations...${NC}"
python3 scripts/verify_translations.py || exit
