"""The application-facing battery-control port."""

from typing import Any, Protocol, runtime_checkable

from .models import Capabilities, InstantControlStatus, InstantOverrideCommand


@runtime_checkable
class BatteryControlPort(Protocol):
    @property
    def capabilities(self) -> Capabilities: ...

    async def connect(self) -> None: ...

    async def close(self) -> None: ...

    async def set_instant_override(self, command: InstantOverrideCommand) -> None: ...

    async def clear_instant_override(self) -> None: ...

    async def instant_control_status(self) -> InstantControlStatus: ...

    async def available_operational_modes(self) -> dict[str, Any]: ...

    async def get_operational_mode(self) -> tuple[int, int]: ...

    async def set_operational_mode(
        self, mode: int, profile_id: int = -1
    ) -> dict[str, Any]: ...
