"""The application-facing cloud-control port."""

from typing import Any, Protocol, runtime_checkable

from .models import Capabilities, InstantControlStatus, InstantOverrideCommand


@runtime_checkable
class CloudControlPort(Protocol):
    @property
    def model(self) -> str: ...

    @property
    def capabilities(self) -> Capabilities: ...

    async def connect(self) -> None: ...

    async def close(self) -> None: ...

    async def device_list(self) -> list[dict[str, Any]]: ...

    async def set_instant_override(self, command: InstantOverrideCommand) -> None: ...

    async def clear_instant_override(self) -> None: ...

    async def instant_control_status(self) -> InstantControlStatus: ...

    async def available_operational_modes(self) -> dict[str, Any]: ...

    async def get_operational_mode(self) -> tuple[int, int]: ...

    async def set_operational_mode(
        self, mode: int, profile_id: int = -1
    ) -> dict[str, Any]: ...

    async def grid_export_limit(self) -> dict[str, Any]: ...

    async def set_grid_export_limit(
        self, limit_kw: float, *, enabled: bool = True
    ) -> dict[str, Any]: ...

    async def grid_import_limit(self) -> dict[str, Any]: ...

    async def set_grid_import_limit(
        self, limit_kw: float, *, enabled: bool = True
    ) -> dict[str, Any]: ...

    async def grid_connection_limit(self) -> dict[str, Any]: ...

    async def set_grid_connection_limit(
        self, limit_a: float, *, enabled: bool = True
    ) -> dict[str, Any]: ...

    async def battery_power_limit(self) -> dict[str, Any]: ...

    async def set_battery_power_limit(
        self, *, max_charge_kw: float | None, max_discharge_kw: float | None
    ) -> dict[str, Any]: ...

    async def solar_power_limit(self) -> dict[str, Any]: ...

    async def set_solar_power_limit(self, limit_kw: float | None) -> dict[str, Any]: ...

    async def battery_export_limitation(self) -> dict[str, Any]: ...

    async def set_battery_export_limitation(self, enabled: bool) -> dict[str, Any]: ...
